workflows:
  flutter-android-release:
    name: Flutter Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      cancel_previous_builds: true
    environment:
      flutter: stable
    scripts:
      - name: Ensure android directory exists
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          ls -la "$CM_BUILD_DIR/android"  # 로그로 디렉토리 확인
      - name: Set up local.properties with verification
        script: |
          FLUTTER_SDK="$HOME/programs/flutter"
          LOCAL_PROP="$CM_BUILD_DIR/android/local.properties"
          echo "flutter.sdk=\( {FLUTTER_SDK}" > " \){LOCAL_PROP}"
          echo "sdk.dir=\( {ANDROID_SDK_ROOT}" >> " \){LOCAL_PROP}"  # Android SDK 경로 보강 (필수 아님 but 안전)
          if [ -f "${LOCAL_PROP}" ]; then
            cat "${LOCAL_PROP}"  # 로그에 파일 내용 출력 → 성공 확인용
            echo "local.properties created successfully"
          else
            echo "Failed to create local.properties"
            exit 1
          fi
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_driver.log
