workflows:
  flutter-android-release:
    name: Flutter Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      cancel_previous_builds: true
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Change to project root (critical fix)
        script: |
          cd "$CM_BUILD_DIR" || exit 1
          # 만약 zip 업로드로 폴더 중첩됐다면 아래 줄 활성화 (주석 해제)
          # cd Over-the-bike-fit || cd over_the_bike_fit || cd Over_-the_bike_fit || echo "No nested folder found"
          pwd  # 로그로 현재 디렉토리 출력 (디버깅용)
          ls -la  # pubspec.yaml 보이는지 확인
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_driver.log
