workflows:
  flutter-android:
    name: Bike Fit Build Final
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Setup and Assets
        script: |
          unzip *.zip
          PROJ=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ"
          # 이미지 자동 배치
          mkdir -p assets
          cp ../assets_final/*.png ./assets/ 2>/dev/null || cp ../assets/*.png ./assets/ 2>/dev/null || true
          # 안드로이드 설정 복구
          flutter create . --platforms android
          flutter pub get
      - name: Build APK
        script: |
          PROJ=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ"
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
