workflows:
  build-apk:
    name: Simple Flutter APK Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
