workflows:
  flutter-android:
    name: Bike Fit Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          unzip *.zip
          PROJ_PATH=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ_PATH"
          flutter create . --platforms android
          flutter pub get
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
