workflows:
  android-workflow:
    name: Bike Fit Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          unzip *.zip
          PROJ=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \;)
          cd "$PROJ"
          flutter create . --platforms android
          flutter pub get
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
